version: "3"

networks:
  nest_network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: 'postgres'
    restart: always
    networks:
      - nest_network
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - "./database/:/var/lib/postgresql/data"


  # server:
  #   build:
  #     context: .
  #     dockerfile: Docker-server
  #   container_name: 'server'
  #   ports: